=== UriAlexandra/OE8BW9WebXML/OE8BW81015/OE8BW9_XMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="vendeglatas">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="etterem" type="etteremTípus" maxOccurs="unbounded"/> 
            <xs:element name="foszakacs" type="foszakacsTípus" maxOccurs="unbounded"/> 
            <xs:element name="szakacs" type="szakacsTípus" maxOccurs="unbounded"/> 
            <xs:element name="gyakornok" type="gyakornokTípus" maxOccurs="unbounded"/> 
            <xs:element name="vendeg" type="vendegTípus" maxOccurs="unbounded"/> 
            <xs:element name="rendeles" type="rendelesTípus" maxOccurs="unbounded"/>    
        </xs:sequence>
    </xs:complexType>

<!-- Kulcsok -->
<xs:key name="etterem_kulcs">
    <xs:selector xpath="etterem"/>
    <xs:field xpath="@ekod"/>
</xs:key>

<xs:key name="foszakacs_kulcs">
    <xs:selector xpath="foszakacs"/>
    <xs:field xpath="@fkod"/>
</xs:key>

<xs:key name="szakacs_kulcs">
    <xs:selector xpath="szakacs"/>
    <xs:field xpath="@szkod"/>
</xs:key>

<xs:key name="gyakornok_kulcs"> 
    <xs:selector xpath="gyakornok"/>
    <xs:field xpath="@gykod"/> 
</xs:key>

<xs:key name="vendeg_kulcs">
    <xs:selector xpath="vendeg"/>
    <xs:field xpath="@vkod"/>
</xs:key>

<xs:key name="rendeles_kulcs">
    <xs:selector xpath="rendeles"/>
    <xs:field xpath="@rkod"/> 
</xs:key>

<!-- Idegenkulcsok -->
<xs:keyref refer="etterem_kulcs" name="etterem_idegen_kulcs">
    <xs:selector xpath="rendeles"/>
    <xs:field xpath="@e_v_e"/>
</xs:keyref> 



<xs:keyref refer="foszakacs_kulcs" name="foszakacs_idegen_kulcs">
    <xs:selector xpath="foszakacs"/>
    <xs:field xpath="@e_v_v"/>
</xs:keyref>

<xs:keyref refer="szakacs_kulcs" name="szakacs_idegen_kulcs">
    <xs:selector xpath="szakacs"/>
    <xs:field xpath="@szkod"/>
</xs:keyref>

<xs:keyref refer="gyakornok_kulcs" name="gyakornok_idegen_kulcs">
    <xs:selector xpath="gyakornok"/>    
    <xs:field xpath="@gkod"/>
</xs:keyref>

<xs:keyref refer="vendeg_kulcs" name="vendeg_idegen_kulcs">
    <xs:selector xpath="rendeles"/>
    <xs:field xpath="@vkod"/>
</xs:keyref>

<xs:keyref refer="rendeles_kulcs" name="rendeles_idegen_kulcs">
    <xs:selector xpath="rendeles"/>
    <xs:field xpath="@v_r"/>
</xs:keyref>

</xs:element>

<!-- Komplex Típusok -->
 <xs:complexType name="etteremTípus">
    <xs:sequence>
        <xs:element name="nev" type="xs:string"/>
        <xs:element name="cím" type="cimTípus"/>
        <xs:element name="csillag" type="xs:integer"/>
    </xs:sequence>
    <xs:attribute name="ekod" type="xs:string" use="required"/>
 </xs:complexType>

    <xs:complexType name="cimTípus">
        <xs:sequence>
            <xs:element name="varos" type="xs:string"/>
            <xs:element name="utca" type="xs:string"/>
            <xs:element name="hazszam" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="foszakacsTípus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="eletkor" type="xs:integer"/>
            <xs:element name="vegzettseg" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="fkod" type="xs:string" use="required"/>
        <xs:attribute name="e_f" type="xs:string" use="required"/> 
    </xs:complexType>

    <xs:complexType name="szakacsTípus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="reszleg" type="xs:string"/>
            <xs:element name="vegzettseg" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="szkod" type="xs:string" use="required"/>
        <xs:attribute name="e_sz" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="gyakornokTípus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="gyakorlat" type="gyakorlatTípus"/>
            <xs:element name="muszak" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="gykod" type="xs:string" use="required"/>
        <xs:attribute name="e_gy" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="gyakorlatTípus">
        <xs:sequence>
            <xs:element name="kezdet" type="xs:string"/>
            <xs:element name="időtartam" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="vendegTípus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="eletkor" type="xs:integer"/>
            <xs:element name="cím" type="cimTípus"/>
        </xs:sequence>
        <xs:attribute name="vkod" type="xs:string" use="required"/>
        <xs:attribute name="e_v" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="rendelesTípus">
        <xs:sequence>
            <xs:element name="osszeg" type="xs:integer"/>
            <xs:element name="etel" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="e_v_v" type="xs:string" use="required"/>
        <xs:attribute name="e_v_e" type="xs:string" use="required"/>
    </xs:complexType>

</xs:schema>

=== UriAlexandra/OE8BW9WebXML/OE8BW81015/OE8BW9_XML.xml
<?xml version="1.0" encoding="UTF-8"?>
<vendeglatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="OE8BW9_XMLSchema.xsd">
    <etterem ekod="e1">
        <nev>Trofea</nev>
        <cím>
            <varos>Budapest</varos>
                <utca>Visegrádi</utca>
                <hazszam> 12</hazszam>
            </cím>
        <csillag>4</csillag>
    </etterem>
    <etterem ekod="e2">
        <nev>Gundel</nev>
        <cím>
            <varos>Budapest</varos>
                <utca>Gundel Károly</utca>
                <hazszam>4</hazszam>
            </cím>
        <csillag>5</csillag>
    </etterem>

 <!-- FoSzakacsok -->
    <foszakacs fkod="f1" e_f="e1">
        <nev>Havas Péter</nev>
        <eletkor>35</eletkor>
        <vegzettseg>Szakközépiskola</vegzettseg>
        <vegzettseg>Institut Paul Bocuse</vegzettseg>
    </foszakacs>

    <foszakacs fkod="f2" e_f="e2">
        <nev>Nagy Károly</nev>
        <eletkor>30</eletkor>
        <vegzettseg>Le Cordon Bleu</vegzettseg>
    </foszakacs>
    
    <!-- Szakacsok -->
     <szakacs szkod="sz1" e_sz="e1">
        <nev>Ötlet Elek</nev>
        <reszleg>Saucier</reszleg>
        <vegzettseg>Szakközépiskola</vegzettseg>
        <vegzettseg>Le Cordon Bleu</vegzettseg>
        <vegzettseg>Institut Paul Bocuse</vegzettseg>
     </szakacs>

     <szakacs szkod="sz2" e_sz="e2">
        <nev>Kocsis Tibor</nev>
        <reszleg>Entremiter</reszleg>
        <vegzettseg>Szakközépiskola</vegzettseg>
        <vegzettseg>Le Cordon Bleu</vegzettseg>
     </szakacs>

     <szakacs szkod="sz3" e_sz="e3">
        <nev>Tálas Levente</nev>
        <reszleg>Gardemenger</reszleg>
        <vegzettseg>Szakközépiskola</vegzettseg>
     </szakacs>

     <szakacs szkod="sz4" e_sz="e4">
        <nev>Szúcs Judit</nev>
        <reszleg>Entremetier</reszleg>
        <vegzettseg>La Cordon Bleu</vegzettseg>
        <vegzettseg>Institut Paul Bocuse</vegzettseg>
     </szakacs>

     <!-- Gyakornokok -->
    <gyakornok gykod="g1" e_gy="e1">
        <nev>Szilágyi István</nev>
        <gyakorlat>
            <kezdet>2021.06.01</kezdet>
            <időtartam>4 hónap</időtartam>
        </gyakorlat>
        <muszak>Délután</muszak>
    </gyakornok>

    <gyakornok gykod="g2" e_gy="e2">
        <nev>Bordás Dávid</nev>
        <gyakorlat>
            <kezdet>2021.08.20</kezdet>
            <időtartam>2 hónap</időtartam>
        </gyakorlat>
        <muszak>Délelőtt</muszak>
        <muszak>Este</muszak>
    </gyakornok>

    <gyakornok gykod="g3" e_gy="e3">
        <nev>Kis Ferenc</nev>
        <gyakorlat>
            <kezdet>2021.09.19</kezdet>
            <időtartam>6 hónap</időtartam>
        </gyakorlat>
        <muszak>Délelőtt</muszak>
        <muszak>Este</muszak>
    </gyakornok>

    <vendeg vkod="v1" e_v="e1">
        <nev>Fekete Péter</nev>
        <eletkor>21</eletkor>
        <cím>
            <varos>Budapest</varos>
                <utca>Visegrádi</utca>
                <hazszam> 12</hazszam>
        </cím>
    </vendeg>
    
    <vendeg vkod="v2" e_v="e2">
        <nev>Fekete Péter</nev>
        <eletkor>21</eletkor>
        <cím>
            <varos>Budapest</varos>
                <utca>Visegrádi</utca>
                <hazszam> 12</hazszam>
        </cím>
    </vendeg>

    <rendeles  e_v_e="v1" e_v_v="e1">
        <osszeg>90000</osszeg>
        <etel>Steak</etel>
    </rendeles>

    <rendeles  e_v_e="v2" e_v_v="e2">
        <osszeg>18000</osszeg>
        <etel>Zsíros kenyér</etel>
    </rendeles>

    <rendeles  e_v_e="v3" e_v_v="e3">
        <osszeg>50000</osszeg>
        <etel>Gundel palacsinta</etel>
    </rendeles>

    <rendeles  e_v_e="v4" e_v_v="e4">
        <osszeg>90000</osszeg>
        <etel>Sajt</etel>
    </rendeles>

</vendeglatas>
