=== UriAlexandra/OE8BW9WebXML/OE8BW9_XMLTask/XMLSchemaOE8BW9.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="ételrendelések">	
		<xs:complexType>
	            <xs:sequence>
	                <xs:element name="rendelés" type="rendelésTipus" maxOccurs="unbounded"/>
	                <xs:element name="megrendelő" type="megrendelőTipus" maxOccurs="unbounded"/>
	                <xs:element name="fizetés" type="fizetésTipus" maxOccurs="unbounded"/>
	                <xs:element name="rendelt" type="rendeltTipus" maxOccurs="unbounded"/>
	                <xs:element name="étel" type="ételTipus" maxOccurs="unbounded"/>
	                <xs:element name="akció" type="akcióTipus" maxOccurs="unbounded"/>
	            </xs:sequence>
		</xs:complexType>
		
		
		<!-- Primary keys -->
		<xs:key name="rendelésKulcs">
            <xs:selector xpath="rendelés"/>
            <xs:field xpath="@RID"/>
        </xs:key>
        
        <xs:key name="megrendelőKulcs">
            <xs:selector xpath="megrendelő"/>
            <xs:field xpath="@MID"/>
        </xs:key>
        
        <xs:key name="fizetésKulcs">
            <xs:selector xpath="fizetés"/>
            <xs:field xpath="@FID"/>
        </xs:key>
        
        <xs:key name="ételKulcs">
            <xs:selector xpath="étel"/>
            <xs:field xpath="@EID"/>
        </xs:key>
        
        <xs:key name="akciöKulcs">
            <xs:selector xpath="akció"/>
            <xs:field xpath="@AID"/>
        </xs:key>
        
        <!-- Foreign keys -->
        <xs:keyref refer="megrendelőKulcs" name="rendelésMegrendelőIdegenKulcs">
            <xs:selector xpath="rendelés"/>
            <xs:field xpath="@MID"/>
        </xs:keyref>  
        
        <xs:keyref refer="rendelésKulcs" name="rendeltRendelésIdegenKulcs">
            <xs:selector xpath="rendelt"/>
            <xs:field xpath="@RID"/>
        </xs:keyref>
        
        <xs:keyref refer="ételKulcs" name="rendeltÉtelIdegenKulcs">
            <xs:selector xpath="rendelt"/>
            <xs:field xpath="@EID"/>
        </xs:keyref>
        
        <xs:keyref refer="ételKulcs" name="akcióÉtelIdegenKulcs">
            <xs:selector xpath="akció"/>
            <xs:field xpath="@EID"/>
        </xs:keyref>
        
        <!-- 1-1 -->
        <xs:unique name="rendelésFizetésEgy">
            <xs:selector xpath="rendelés"/>
            <xs:field xpath="@FID"/>
        </xs:unique>
    </xs:element>	    
      
    <!-- Sajat tipusok -->
    <xs:complexType name="rendelésTipus">
		<xs:sequence>
			<xs:element name="dátum" type="xs:date"/>          
			<xs:element name="kiszállítási_cím" type="xs:string"/> 
			<xs:element name="összeg" type="xs:integer"/>   	            
		</xs:sequence>
		<xs:attribute name="RID" type="xs:integer" use="required"/>
		<xs:attribute name="MID" type="xs:integer" use="required"/>
		<xs:attribute name="FID" type="xs:integer" use="required"/>
   	</xs:complexType>  
   	
   	<xs:complexType name="megrendelőTipus">
		<xs:sequence>
			<xs:element name="visszatérő_vendég">         
				<xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="igen"/>
                        <xs:enumeration value="nem"/>
                    </xs:restriction>
                </xs:simpleType> 
            </xs:element>
			<xs:element name="telefonszám" type="xs:string"/> 
			<xs:element name="név" type="xs:string"/>   	            
		</xs:sequence>
		<xs:attribute name="MID" type="xs:integer" use="required"/>
   	</xs:complexType>  
   	
   	 <xs:complexType name="fizetésTipus">
		<xs:sequence>
			<xs:element name="átvitel_ideje" type="xs:date"/>          
			<xs:element name="kupon"> 
				<xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="igen"/>
                        <xs:enumeration value="nem"/>
                    </xs:restriction>
                </xs:simpleType> 
            </xs:element>
			<xs:element name="fizetés_módja">  
			<xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="bankkártya"/>
                        <xs:enumeration value="készpénz"/>
                        <xs:enumeration value="szép-kártya"/>
                    </xs:restriction>
                </xs:simpleType> 
            </xs:element> 	            
		</xs:sequence>	
		<xs:attribute name="FID" type="xs:integer" use="required"/>
   	</xs:complexType>
   	
   	<xs:complexType name="rendeltTipus">
		<xs:sequence>
			<xs:element name="mennyiség" type="xs:integer"/>   	            
		</xs:sequence>
		<xs:attribute name="RID" type="xs:integer" use="required"/>
		<xs:attribute name="EID" type="xs:integer" use="required"/>
   	</xs:complexType>     	
   	     		
	<xs:complexType name="ételTipus">
		<xs:sequence>
			<xs:element name="név" type="xs:string"/>          
			<xs:element name="ár" type="xs:integer"/> 
			<xs:element name="allergén" type="xs:string" maxOccurs="unbounded"/>  
			<xs:element name="típus" type="xs:string"/>    	            
		</xs:sequence>
		<xs:attribute name="EID" type="xs:integer" use="required"/>
   	</xs:complexType> 
   	
   	<xs:complexType name="akcióTipus">
		<xs:sequence>
			<xs:element name="időtartam">
				<xs:complexType>
                    <xs:sequence>  
                      	<xs:element name="kezdete" type="xs:date"/> 
                      	<xs:element name="vége" type="xs:date"/> 
                    </xs:sequence>
                </xs:complexType>
            </xs:element>    
			<xs:element name="leárazás" type="xs:integer"/>  	            
		</xs:sequence>
		<xs:attribute name="EID" type="xs:integer" use="required"/>
		<xs:attribute name="AID" type="xs:integer" use="required"/>
   	</xs:complexType>  
	
</xs:schema>

=== UriAlexandra/OE8BW9WebXML/OE8BW9_XMLTask/MOD_OE8BW9XML.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Gyökérelem --><ételrendelések xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaOE8BW9.xsd">
    	
    <!-- =======================
	     RENDELÉSEK
	     ======================= -->
    	
    <!-- RID = rendelés azonosító, MID = megrendelő azonosító, FID = fizetés azonosító -->
    	
    <rendelés FID="1" MID="1" RID="1">
        		
        <dátum>2025-01-01</dátum>
        		
        <kiszállítási_cím>Arany János utca 1.</kiszállítási_cím>
        		
        <összeg>6750</összeg>
        	
    </rendelés>
    	
	
    <rendelés FID="2" MID="2" RID="2">
          
        <!-- rendelésekkel 1:N kapcsolatban van -->
        		
        <dátum>2025-02-02</dátum>
        		
        <kiszállítási_cím>Irinyi János utca 10.</kiszállítási_cím>
        		
        <összeg>6060</összeg>
        	
    </rendelés>
    	
	
    <rendelés FID="3" MID="1" RID="3">
        		
        <dátum>2025-10-10</dátum>
        		
        <kiszállítási_cím>Petőfi Séndor utca 1.</kiszállítási_cím>
        		
        <összeg>10880</összeg>
        	
    </rendelés>
    	
	
    <rendelés FID="4" MID="3" RID="4">
        		
        <dátum>2025-11-04</dátum>
        		
        <kiszállítási_cím>Kuruc József utca 23.</kiszállítási_cím>
        		
        <összeg>9470</összeg>
        	
    </rendelés>
    	
	
    <!-- =======================
	     MEGRENDELŐK
	     ======================= -->
    	
    <!-- MID = megrendelő azonosító -->
    	
    <megrendelő MID="1">
        		
        <visszatérő_vendég>igen</visszatérő_vendég>
        		
        <telefonszám>0620000001</telefonszám>
        		
        <név>Kerekes Ferenc</név>
        	
    </megrendelő>
    	
	
    <megrendelő MID="2">
        		
        <visszatérő_vendég>nem</visszatérő_vendég>
        		
        <telefonszám>0620202020</telefonszám>
        		
        <név>Kiss Sándor</név>
        	
    </megrendelő>
    	
	
    <megrendelő MID="3">
        		
        <visszatérő_vendég>igen</visszatérő_vendég>
        		
        <telefonszám>0620987654321</telefonszám>
        		
        <név>Kékesi Albert</név>
        	
    </megrendelő>
    	
	
    <!-- =======================
	     FIZETÉSEK
	     ======================= -->
    	
    <!-- FID = fizetés azonosító -->
    	
    <fizetés FID="1">
        		
        <átvitel_ideje>2025-01-01</átvitel_ideje>
        		
        <!-- XSD-ben ez 1:1 kapcsolat a rendeléshez-->
        		
        <kupon>nem</kupon>
        		
        <fizetés_módja>készpénz</fizetés_módja>
        	
    </fizetés>
    	
	
    <fizetés FID="2">
        		
        <átvitel_ideje>2025-02-09</átvitel_ideje>
        		
        <kupon>igen</kupon>
        		
        <fizetés_módja>bankkártya</fizetés_módja>
        	
    </fizetés>
    	
	
    <fizetés FID="3">
        		
        <átvitel_ideje>2025-10-11</átvitel_ideje>
        		
        <kupon>igen</kupon>
        		
        <fizetés_módja>készpénz</fizetés_módja>
        	
    </fizetés>
    	
	
    <fizetés FID="4">
        		
        <átvitel_ideje>2025-11-07</átvitel_ideje>
        		
        <kupon>nem</kupon>
        		
        <fizetés_módja>bankkártya</fizetés_módja>
        	
    </fizetés>
    	
	
    <!-- =======================
	     RENDELT TÉTELEK
	     ======================= -->
    	
    <!-- Kapcsolótábla rendelés és étel között: RID + EID -->
    	
    <rendelt EID="1" RID="1">
        		
        <!-- N:N kapcsolatot old fel: rendelés ↔ étel -->
        		
        <mennyiség>2</mennyiség>
        		
        <tétel_ár>2250</tétel_ár>
        		
        <megjegyzés>extra sajt</megjegyzés>
        	
    </rendelt>
    	
	
    <rendelt EID="6" RID="1">
        		
        <mennyiség>1</mennyiség>
        		
        <tétel_ár>2550</tétel_ár>
        		
        <megjegyzés>gluténmentes tészta</megjegyzés>
        	
        <megjegyzés>saját kérés</megjegyzés>
    </rendelt>
    	
	
    <rendelt EID="3" RID="2">
        		
        <mennyiség>1</mennyiség>
        		
        <tétel_ár>2720</tétel_ár>
        		
        <megjegyzés>normál adag</megjegyzés>
        	
    </rendelt>
    	
	
    <rendelt EID="5" RID="2">
        		
        <mennyiség>2</mennyiség>
        		
        <tétel_ár>1670</tétel_ár>
        		
        <megjegyzés>öntet nélkül</megjegyzés>
        	
    </rendelt>
    	
	
    <rendelt EID="4" RID="3">
        		
        <mennyiség>4</mennyiség>
        		
        <tétel_ár>2720</tétel_ár>
        		
        <megjegyzés>extra sajt</megjegyzés>
        	
    </rendelt>
    	
	
    <rendelt EID="2" RID="4">
        		
        <mennyiség>3</mennyiség>
        		
        <tétel_ár>2250</tétel_ár>
        		
        <megjegyzés>csípős</megjegyzés>
        	
    </rendelt>
    	
	
    <rendelt EID="3" RID="4">
        		
        <mennyiség>1</mennyiség>
        		
        <tétel_ár>2720</tétel_ár>
        		
        <megjegyzés>extra szezámmag</megjegyzés>
        	
    </rendelt>
    	
	
    <!-- =======================
	     ÉTELEK LISTÁJA
	     ======================= -->
    	
    <!-- EID = étel azonosító -->
    	
    <étel EID="1">
        		
        <név>Hawaii pizza</név>
         	
        <!--akciók és rendelt tételek is erre hivatkoznak-->
        		
        <ár>2750</ár>
        		
        <!-- Több allergén elem is lehet -->
        		
        <allergén>Glutén</allergén>
        		
        <allergén>Tojás</allergén>
        		
        <típus>Pizza</típus>
        	
    </étel>
    	
	
    <étel EID="2">
        		
        <név>Piedone pizza</név>
        		
        <ár>2250</ár>
        		
        <allergén>Glutén</allergén>
        		
        <allergén>Tojás</allergén>
        		
        <típus>Pizza</típus>
        	
    </étel>
    	
	
    <étel EID="3">
        		
        <név>Szezámos csirke box</név>
        		
        <ár>2720</ár>
        		
        <allergén>Szezámmag</allergén>
        		
        <típus>Húsétel</típus>
        	
    </étel>
    	
	
    <étel EID="4">
        		
        <név>Extrasajtos Gyros tál</név>
        		
        <ár>2720</ár>
        		
        <allergén>Szezámmag</allergén>
        		
        <allergén>Glutén</allergén>
        		
        <típus>Húsétel</típus>
        	
    </étel>
    	
	
    <étel EID="5">
        		
        <név>Görög saláta</név>
        		
        <ár>1670</ár>
        		
        <!-- Allergén üres esetben nincs feltüntetett allergén -->
        		
        <allergén/>
        		
        <típus>Saláta</típus>
        	
    </étel>
    	
	
    <étel EID="6">
        		
        <név>4sajtos</név>
        		
        <ár>2550</ár>
        		
        <allergén>Glutén</allergén>
        		
        <allergén>Tojás</allergén>
        		
        <típus>Pizza</típus>
        	
    </étel>
    	
	
    <!-- =======================
	     AKCIÓK
	     ======================= -->
    	
    <!-- AID = akció azonosító, EID = érintett étel -->
    	
    <akció AID="1" EID="1">
        		
        <időtartam>
            			
            <kezdete>2025-01-01</kezdete>
            		
            <!--Egy ételnek több akciója lehet → 1:N kapcsolat-->
            			
            <vége>2025-02-01</vége>
            		
        </időtartam>
        		
        <leárazás>10</leárazás>
        	
    </akció>
    	
	
    <akció AID="2" EID="1">
        		
        <időtartam>
            			
            <kezdete>2025-06-01</kezdete>
            			
            <vége>2025-09-01</vége>
            		
        </időtartam>
        		
        <leárazás>10</leárazás>
        	
    </akció>
    	
	
    <akció AID="3" EID="2">
        		
        <időtartam>
            			
            <kezdete>2025-10-31</kezdete>
            			
            <vége>2025-11-30</vége>
            		
        </időtartam>
        		
        <leárazás>50</leárazás>
        	
    </akció>
    	
	
    <akció AID="4" EID="6">
        		
        <időtartam>
            			
            <kezdete>2025-04-15</kezdete>
            			
            <vége>2025-05-15</vége>
            		
        </időtartam>
        		
        <leárazás>15</leárazás>
        	
    </akció>
    	
	
    <akció AID="5" EID="6">
        		
        <időtartam>
            			
            <kezdete>2025-09-01</kezdete>
            			
            <vége>2025-11-30</vége>
            		
        </időtartam>
        		
        <leárazás>30</leárazás>
        	
    </akció>
    
</ételrendelések>

=== UriAlexandra/OE8BW9WebXML/OE8BW9_XMLTask/OE8BW9.xml
<?xml version="1.0" encoding="UTF-8"?>

<ételrendelések xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaOE8BW9.xsd">
	<!-- rendelések -->
	<rendelés RID="1" MID="1" FID="1">
		<dátum>2025-01-01</dátum>
		<kiszállítási_cím>Arany_János_utca_1.</kiszállítási_cím>
		<összeg>6750</összeg>
	</rendelés>
	
	<rendelés RID="2" MID="2" FID="2">
		<dátum>2025-02-02</dátum>
		<kiszállítási_cím>Nagy_Lasjos_király_útja_2.</kiszállítási_cím>
		<összeg>6060</összeg>
	</rendelés>
	
	<rendelés RID="3" MID="1" FID="3">
		<dátum>2025-10-10</dátum>
		<kiszállítási_cím>Arany_János_utca_1.</kiszállítási_cím>
		<összeg>10880</összeg>
	</rendelés>
	
	<rendelés RID="4" MID="3" FID="4">
		<dátum>2025-11-04</dátum>
		<kiszállítási_cím>Kuruc_utca_23.</kiszállítási_cím>
		<összeg>9470</összeg>
	</rendelés>
	
	<!-- megrendelők -->
	<megrendelő MID="1">
		<visszatérő_vendég>igen</visszatérő_vendég>
		<telefonszám>0620000001</telefonszám>
		<név>Első_Elemér</név>
	</megrendelő>
	
	<megrendelő MID="2">
		<visszatérő_vendég>nem</visszatérő_vendég>
		<telefonszám>0620202020</telefonszám>
		<név>Második_Mária</név>
	</megrendelő>
	
	<megrendelő MID="3">
		<visszatérő_vendég>nem</visszatérő_vendég>
		<telefonszám>0620987654321</telefonszám>
		<név>Kis_Pista</név>
	</megrendelő>
	
	<!-- fizetések -->
	<fizetés FID="1">
		<átvitel_ideje>2025-01-01</átvitel_ideje>
		<kupon>nem</kupon>
		<fizetés_módja>készpénz</fizetés_módja>
	</fizetés>
	
	<fizetés FID="2">
		<átvitel_ideje>2025-02-09</átvitel_ideje>
		<kupon>igen</kupon>
		<fizetés_módja>bankkártya</fizetés_módja>
	</fizetés>
	
	<fizetés FID="3">
		<átvitel_ideje>2025-10-11</átvitel_ideje>
		<kupon>igen</kupon>
		<fizetés_módja>készpénz</fizetés_módja>
	</fizetés>
	
	<fizetés FID="4">
		<átvitel_ideje>2025-11-07</átvitel_ideje>
		<kupon>nem</kupon>
		<fizetés_módja>szép-kártya</fizetés_módja>
	</fizetés>
	
	<!-- megrendelt ételek kapcsoló -->
	<rendelt RID="1" EID="1">
		<mennyiség>2</mennyiség>
	</rendelt>
	
	<rendelt RID="1" EID="6">
		<mennyiség>1</mennyiség>
	</rendelt>
	
	<rendelt RID="2" EID="3">
		<mennyiség>1</mennyiség>
	</rendelt>
	
	<rendelt RID="2" EID="5">
		<mennyiség>2</mennyiség>
	</rendelt>
	
	<rendelt RID="3" EID="4">
		<mennyiség>4</mennyiség>
	</rendelt>
	
	<rendelt RID="4" EID="2">
		<mennyiség>3</mennyiség>
	</rendelt>
	
	<rendelt RID="4" EID="3">
		<mennyiség>1</mennyiség>
	</rendelt>
	
	<!-- ételek -->
	<étel EID="1">
		<név>Hawaii</név>
		<ár>2250</ár>
		<allergén>Glutén</allergén>
		<allergén>Tojás</allergén>
		<típus>Pizza</típus>
	</étel>
	
	<étel EID="2">
		<név>Piedone</név>
		<ár>2250</ár>
		<allergén>Glutén</allergén>
		<allergén>Tojás</allergén>
		<típus>Pizza</típus>
	</étel>
	
	<étel EID="3">
		<név>Szezámos_csirke_box</név>
		<ár>2720</ár>
		<allergén>Szezámmag</allergén>
		<típus>Húsétel</típus>
	</étel>
	
	<étel EID="4">
		<név>Gyros_tál</név>
		<ár>2720</ár>
		<allergén>Szezámmag</allergén>
		<allergén>Glutén</allergén>
		<típus>Húsétel</típus>
	</étel>
	
	<étel EID="5">
		<név>Görög_saláta</név>
		<ár>1670</ár>
		<allergén></allergén>
		<típus>Saláta</típus>
	</étel>
	
	<étel EID="6">
		<név>4sajtos</név>
		<ár>2550</ár>
		<allergén>Glutén</allergén>
		<allergén>Tojás</allergén>
		<típus>Pizza</típus>
	</étel>
	
	<!-- akciók -->
	<akció AID="1" EID="1">
		<időtartam>
			<kezdete>2025-01-01</kezdete>
			<vége>2025-02-01</vége>
		</időtartam>
		<leárazás>10</leárazás>
	</akció>
	
	<akció AID="2" EID="1">
		<időtartam>
			<kezdete>2025-06-01</kezdete>
			<vége>2025-09-01</vége>
		</időtartam>
		<leárazás>10</leárazás>
	</akció>
	
	<akció AID="3" EID="2">
		<időtartam>
			<kezdete>2025-10-31</kezdete>
			<vége>2025-11-30</vége>
		</időtartam>
		<leárazás>50</leárazás>
	</akció>
	
	<akció AID="4" EID="6">
		<időtartam>
			<kezdete>2025-04-15</kezdete>
			<vége>2025-05-15</vége>
		</időtartam>
		<leárazás>15</leárazás>
	</akció>
	
	<akció AID="5" EID="6">
		<időtartam>
			<kezdete>2025-09-01</kezdete>
			<vége>2025-11-30</vége>
		</időtartam>
		<leárazás>30</leárazás>
	</akció>
</ételrendelések>
